# Generated by Django 4.1.3 on 2022-11-29 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("msm_backend", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="feedingcost",
            options={"ordering": ["monster__name", "cost"]},
        ),
        migrations.AlterModelOptions(
            name="maxamount",
            options={"ordering": ["monster__name", "level"]},
        ),
        migrations.AlterUniqueTogether(
            name="earning",
            unique_together={("monster", "level")},
        ),
        migrations.AlterUniqueTogether(
            name="feedingcost",
            unique_together={("monster", "level")},
        ),
        migrations.AlterUniqueTogether(
            name="maxamount",
            unique_together={("monster", "level")},
        ),
    ]
