# Generated by Django 4.1.3 on 2022-11-29 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "msm_backend",
            "0002_alter_feedingcost_options_alter_maxamount_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="earning",
            options={"ordering": ["monster", "level"]},
        ),
        migrations.AlterField(
            model_name="breedingcombination",
            name="monster",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="breeding_combinations",
                to="msm_backend.monster",
            ),
        ),
        migrations.AlterField(
            model_name="breedingcombination",
            name="monster_1",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="monster_1",
                to="msm_backend.monster",
            ),
        ),
        migrations.AlterField(
            model_name="breedingcombination",
            name="monster_2",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="monster_2",
                to="msm_backend.monster",
            ),
        ),
    ]
