# Generated by Django 4.1.3 on 2022-11-29 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("msm_backend", "0003_alter_earning_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="monster",
            name="egg",
        ),
        migrations.RemoveField(
            model_name="monster",
            name="image",
        ),
        migrations.RemoveField(
            model_name="monster",
            name="portrait",
        ),
        migrations.AddField(
            model_name="monster",
            name="egg_image",
            field=models.ImageField(
                default="msm_backend/images/util/default.png",
                upload_to="msm_backend/images/monsters/eggs",
            ),
        ),
        migrations.AddField(
            model_name="monster",
            name="main_image",
            field=models.ImageField(
                default="msm_backend/images/util/default.png",
                upload_to="msm_backend/images/monsters/main",
            ),
        ),
        migrations.AddField(
            model_name="monster",
            name="portrait_image",
            field=models.ImageField(
                default="msm_backend/images/util/default.png",
                upload_to="msm_backend/images/monsters/portraits",
            ),
        ),
        migrations.AlterField(
            model_name="breedingcombination",
            name="monster_1",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="msm_backend.monster",
            ),
        ),
        migrations.AlterField(
            model_name="breedingcombination",
            name="monster_2",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="msm_backend.monster",
            ),
        ),
        migrations.AlterField(
            model_name="monster",
            name="islands",
            field=models.ManyToManyField(blank=True, to="msm_backend.island"),
        ),
    ]
