# Generated by Django 4.1.3 on 2022-11-29 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("msm_backend", "0004_remove_monster_egg_remove_monster_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="monster",
            name="breeding_time",
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name="monster",
            name="elements",
            field=models.ManyToManyField(to="msm_backend.element"),
        ),
        migrations.AlterField(
            model_name="monster",
            name="islands",
            field=models.ManyToManyField(to="msm_backend.island"),
        ),
    ]
